#!/bin/bash

TODO_NOTES_DIR=$TODO_DIR/notes
TODO_NOTE_TAG="note:"
TODO_NOTE_EXT=${TODO_NOTE_EXT:-.txt}

usage() {
  echo "    $(basename "$0") ITEM#"
  echo "      Adds a note to the task on line ITEM#. IF exists note, Opens in EDITOR the note related with the task on line ITEM#"
}

getnotepathfromtext() {
  # Parameters: $1: task text
  # Preconditions: none
  # Postcondition:
  #   $notepath contains note file path
  esctitle=$(echo "$1" | sed "s/ ${TODO_NOTE_TAG}//" | sed "s/[ 　/\\?]/-/g" | sed "s/\(-\)\+/-/g")
  notepath="$TODO_NOTES_DIR/${esctitle}${TODO_NOTE_EXT}"
}

getnotepathfromnumber() {
  # Parameters: $1: task number
  # Preconditions: $errmsg contains usage message.
  # Postcondition:
  #   $notename contains note name, if task has note.
  #   $todo contains the task name
  item="$1"
  getTodo "$item"
  # shellcheck disable=SC2154
  getnotepathfromtext "$todo"
}

existsnotefromtext() {
  # Parameters: $1: task text
  # Preconditions: none
  # Postcondition: none
  if [[ "$1" =~ ${TODO_NOTE_TAG} ]] ; then
    return 0
  else
    return 1
  fi
}

editnote() {
  # Parameter:: $1: Path of the file to edit
  # Preconditions: none
  # Postcondition: none
  if [ "$EDITOR" ] ; then
    $EDITOR "$1"
  else
    echo The EDITOR environment variable is not set.
  fi
}

if [ "$1" = "usage" ] || [ $# != 2 ] ; then
  usage
  exit 0
fi
shift

# shellcheck disable=SC2034
errmsg="usage: $TODO_SH $(basename "$0") ITEM#"
getnotepathfromnumber "$1"

if existsnotefromtext "${todo}" ; then
  editnote "${notepath}"
else
  # Create notes directory if doesn't exist
  [ -d "$TODO_NOTES_DIR" ] || mkdir -p "$TODO_NOTES_DIR" 2> /dev/null || die "Error: $TODO_NOTES_DIR is not a directory"

  title="$todo"
  echo \# "$title" > "${notepath}"

  # Append note tag to task
  sed -i "${item} s/$/ ${TODO_NOTE_TAG}/" "$TODO_FILE"

  getTodo "$item"
  echo "${item}" "${todo}"
  echo TODO: Note added to task "${item}".

  echo "Edit note?  (y/n)"
  read ANSWER
  if [ "$ANSWER" = "y" ] ; then
    editnote "${notepath}"
  fi
fi

