#!/bin/bash

# TODO: note名重複

TODO_NOTES_DIR=$TODO_DIR/notes
TODO_NOTE_TAG="note:"
TODO_NOTE_EXT=${TODO_NOTE_EXT:-.txt}
TODO_NOTE_IS_OPEN=${TODO_NOTE_IS_OPEN:-1} # 0:no open, 1:open, 2:confirm

usage() {
  echo "    $(basename "$0") ITEM#"
  echo "      Adds a note to the task on line ITEM#. IF exists note, Opens in EDITOR the note related with the task on line ITEM#"
}

existsnotefromtext() {
  # Parameters: $1: task text
  # Preconditions: none
  # Postcondition: none
  if [[ "$1" =~ ${TODO_NOTE_TAG} ]] ; then
    return 0
  else
    return 1
  fi
}

editnote() {
  # Parameter:: $1: Path of the file to edit
  # Preconditions: none
  # Postcondition: none
  if [ "$EDITOR" ] ; then
    $EDITOR "$1"
  else
    echo The EDITOR environment variable is not set.
  fi
}

if [ "$1" = "usage" ] || [ $# != 2 ] ; then
  usage
  exit 0
fi
shift

errmsg="usage: $TODO_SH $(basename "$0") ITEM# or $TODO_SH $(basename "$0") NEW_TASK_NAME"
expr "$1" + 1 > /dev/null 2>&1
ret=$?
if [ ${ret} -ge 2 ] ; then
  if "$TODO_SH" command add "$@" ; then
      # getting the number item: it's simply the last item added to the file
      line=`wc -l "$TODO_FILE" | cut -d' ' -f1`
  fi
else
  line=$1
fi

getTodo "$line"
todo="${todo#([A-Z]) }"
esctitle=$(echo "$todo" | sed "s/ ${TODO_NOTE_TAG}//" | sed "s/[ 　/\\?]/-/g" | sed "s/\(-\)\+/-/g")
notepath="$TODO_NOTES_DIR/${esctitle}${TODO_NOTE_EXT}"

if existsnotefromtext "${todo}" ; then
  editnote "${notepath}"
else
  # Create notes directory if doesn't exist
  [ -d "$TODO_NOTES_DIR" ] || mkdir -p "$TODO_NOTES_DIR" 2> /dev/null || die "Error: $TODO_NOTES_DIR is not a directory"

  title="$todo"
  echo \# "$title" > "${notepath}"

  # Append nrte tag to task
  sed -i "${line} s/$/ ${TODO_NOTE_TAG}/" "$TODO_FILE"

  echo "TODO: Note added to task ${line}."

  if [ "${TODO_NOTE_IS_OPEN}" = 2 ] ; then
    echo "Edit note?  (y/n)"
    read ANSWER
    if [ "$ANSWER" = "y" ] ; then
      TODO_NOTE_IS_OPEN=1
    fi
  fi
  if [ "${TODO_NOTE_IS_OPEN}" = 1 ] ; then
    editnote "${notepath}"
  fi
fi

